
FROM python:3.8-slim-buster

WORKDIR /app

ADD . /app

RUN pip install --no-cache-dir -r requirements.txt -i https://mirrors.aliyun.com/pypi/simple/ 

RUN mkdir -p /var/lib/sqlite

EXPOSE 80

VOLUME /var/lib/sqlite

CMD ["python", "scrapper.py"]
