version: '3.8'
services:
  flask:
    build: ./flask
    ports:
      - 5000:5000
    volumes:
      - data_volume:/var/lib/sqlite
      - ./backup.sh:/app/backup.sh
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "3m"
        max-file: "1"

  scrapper:
    build: ./scrapper
    volumes:
      - data_volume:/var/lib/sqlite
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "3m"
        max-file: "1"

  nginx:
    build: ./nginx
    ports:
      - 80:80
      - 443:443
    volumes: #链接方式
      # - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      # - ./nginx/proxy_params:/etc/nginx/proxy_params
      # - ./nginx/nginx_index:/var/www/Nginx_Index
      # - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      # - ./nginx/cert.pem:/etc/nginx/cert.pem
      # - ./nginx/key.pem:/etc/nginx/key.pem
      - ./nginx:/etc/nginx
    restart: unless-stopped
    logging:
      driver: "json-file"

      options:
        max-size: "3m"
        max-file: "1"

volumes:
  data_volume: